export const seedProductsData = [
  {
    id: 7,
    name: "Sample Product 1",
    brand: "Sample Brand",
    description: "This is a sample product description.",
    price: 25.99,
    discount: 0.1,
    image_urls: ["/placeholder.svg"],
    category: "Makeup",
    stock_quantity: 50,
    rating: 4.2,
    reviews: 120,
  },
  {
    id: 8,
    name: "Sample Product 2",
    brand: "Sample Brand",
    description: "This is another sample product description.",
    price: 39.5,
    discount: 0.2,
    image_urls: ["/placeholder.svg"],
    category: "Skincare",
    stock_quantity: 30,
    rating: 4.5,
    reviews: 85,
  },
  {
    id: 9,
    name: "Sample Product 3",
    brand: "Sample Brand",
    description: "This is yet another sample product description.",
    price: 15.0,
    discount: 0.05,
    image_urls: ["/placeholder.svg"],
    category: "Haircare",
    stock_quantity: 75,
    rating: 4.0,
    reviews: 200,
  },
]
